name: bohiba
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  flutter_screenutil: ^5.9.0
  package_info_plus: ^8.1.2
  universal_html: ^2.2.4
  url_launcher: ^6.3.2
  flutter_device_type: ^0.4.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  eva_icons_flutter:
  remixicon: ^1.0.0
  marquee_text: ^2.5.0+1
  auto_size_text: ^3.0.0
  pin_code_fields: ^8.0.1
  badges: ^3.1.2
  carousel_slider: ^5.0.0
  persistent_bottom_nav_bar: ^6.2.1
  http: ^1.0.0
  equatable: ^2.0.5
  image_picker: ^1.1.2
  path_provider: ^2.0.14
  flutter_masked_text2: ^0.9.1
  intl: ^0.19.0
  local_auth: ^2.1.6
  share_plus: ^10.1.3
  gap: ^3.0.1
  fluttertoast: ^8.2.12
  table_calendar: ^3.0.9
  flutter_rating: ^2.0.2
  widgets_easier: ^0.0.9
  permission_handler: ^11.3.1
  geocoding: ^3.0.0
  geolocator: ^14.0.1
  dio: ^5.8.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.0
  device_info_plus: ^11.3.0
  pull_to_refresh_flutter3: ^2.0.2
  readmore: ^3.0.0
  # google_mlkit_text_recognition: ^0.15.0
  image: ^4.5.4
  fl_chart: ^0.69.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_code_metrics: ^4.19.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  analyzer: ^4.7.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/files/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
